[package]
name = "thumper-blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
rand = "0.8.5"
lazy_static = "1.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = [
  "console",
  "Window",
  "Performance",
] }
