# WASM テスト設定
[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ["-g"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "-g"]

[package.metadata.wasm-pack.profile.test]
wasm-opt = false